apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: mdumos4hz-go
  janus-idp.io/tekton: mdumos4hz-go
  backstage.io/kubernetes-id: mdumos4hz-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: mdumos4hz-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
