apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: mdumos4hz-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: mdumos4hz-go 
  name: mdumos4hz-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: mdumos4hz-go 
